"""Professional HTML pattern documents (print-to-PDF workflow).

The generator produces a self-contained HTML document with cover info,
materials, abbreviations, round-by-round instructions with stated stitch
counts, and the validation verdict — ready to print or share.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

from .generator import generate_pdf  # noqa: F401  (legacy text fallback)
from ..visualization import measure_pattern

ABBREVIATION_GLOSSARY = {
    "ch": "Chain",
    "sl st": "Slip Stitch",
    "sc": "Single Crochet",
    "hdc": "Half Double Crochet",
    "dc": "Double Crochet",
    "tr": "Treble Crochet",
    "inc": "Increase",
    "dec": "Decrease",
    "sc2tog": "Single Crochet 2 Together",
    "dc2tog": "Double Crochet 2 Together",
    "MR": "Magic Ring",
}

STATUS_COLORS = {
    "PASS": ("#27AE60", "All stitch counts verified"),
    "PASS_WITH_WARNINGS": ("#F39C12", "Verified with warnings — review before starting"),
    "NEEDS_REVIEW": ("#95A5A6", "Needs manual review"),
    "ERROR": ("#E74C3C", "Errors found — fix before crocheting"),
}


class PDFConfig:
    """Configuration for the pattern document."""

    def __init__(
        self,
        designer_name: str = "",
        pattern_title: str = "",
        include_materials: bool = True,
        include_abbreviations: bool = True,
        include_validation: bool = True,
        footer_note: str = "Generated by Crochet Pattern Checker",
    ):
        self.designer_name = designer_name
        self.pattern_title = pattern_title
        self.include_materials = include_materials
        self.include_abbreviations = include_abbreviations
        self.include_validation = include_validation
        self.footer_note = footer_note


def _esc(t) -> str:
    return str(t).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def generate_pdf_html(pattern, validation_report=None, config: "PDFConfig | None" = None) -> str:
    """Render a complete print-ready HTML document for a parsed pattern."""
    config = config or PDFConfig()
    report = validation_report
    items = pattern.rounds or pattern.rows or []
    label = "Round" if pattern.rounds else "Row"
    title = config.pattern_title or getattr(pattern.metadata, "title", "") or "Crochet Pattern"

    el = []
    el.append("<!DOCTYPE html>")
    el.append("<html><head><meta charset=\"utf-8\">")
    el.append(f"<title>{_esc(title)}</title>")
    el.append(
        "<style>"
        "body{font-family:Georgia,serif;max-width:720px;margin:40px auto;color:#2C3E50;line-height:1.5;}"
        "h1{font-size:28px;margin-bottom:2px;}"
        ".designer{color:#7F8C8D;font-style:italic;margin-bottom:18px;}"
        "table{border-collapse:collapse;width:100%;margin:14px 0;}"
        "td,th{border:1px solid #BDC3C7;padding:6px 10px;text-align:left;}"
        "th{background:#F4F6F7;}"
        ".round{margin:6px 0;}"
        ".count{color:#16A085;font-weight:bold;}"
        ".banner{padding:10px 14px;border-radius:6px;font-weight:bold;margin:18px 0;}"
        ".err{color:#C0392B;} .warn{color:#B9770E;}"
        "footer{margin-top:30px;color:#95A5A6;font-size:12px;border-top:1px solid #BDC3C7;padding-top:8px;}"
        "@media print{body{margin:12mm;}}"
        "</style></head><body>"
    )

    # ---- cover ----
    el.append(f"<h1>{_esc(title)}</h1>")
    byline = []
    if config.designer_name:
        byline.append(f"Designed by {_esc(config.designer_name)}")
    byline.append(date.today().strftime("%B %d, %Y"))
    el.append(f"<div class=\"designer\">{' &middot; '.join(byline)}</div>")

    # ---- validation banner ----
    if config.include_validation and report is not None:
        status = report.overall_status.value if hasattr(report.overall_status, "value") else str(report.overall_status)
        color, note = STATUS_COLORS.get(status, ("#95A5A6", ""))
        el.append("<h2>Validation Report</h2>")
        el.append(f"<div class=\"banner\" style=\"background:{color}22;border:1px solid {color};color:{color}\">"
                  f"{_esc(status.replace('_', ' '))} &middot; Score {report.score}/100 &mdash; {_esc(note)}</div>")
        if report.errors:
            el.append("<h3>Validation Errors</h3><ul>")
            for e in report.errors:
                el.append(f"<li class=\"err\">[{_esc(e.location)}] {_esc(e.message)}</li>")
            el.append("</ul>")
        if report.warnings:
            el.append("<h3>Warnings</h3><ul>")
            for w in report.warnings:
                el.append(f"<li class=\"warn\">[{_esc(w.location)}] {_esc(w.message)}</li>")
            el.append("</ul>")

    # ---- finished measurements ----
    try:
        m = measure_pattern(pattern)
        if m.max_stitch_count > 0:
            el.append("<h2>Finished Measurements</h2><table>")
            el.append(f"<tr><th>Total {label}s</th><td>{m.total_rounds}</td></tr>")
            el.append(f"<tr><th>Max stitches per {label.lower()}</th><td>{m.max_stitch_count}</td></tr>")
            if m.max_diameter_inches > 0:
                el.append(f"<tr><th>Approx. diameter</th><td>{m.max_diameter_inches:.2f} in ({m.max_radius_mm*2:.0f} mm)</td></tr>")
            if m.total_height_inches > 0:
                el.append(f"<tr><th>Approx. height</th><td>{m.total_height_inches:.2f} in ({m.total_height_mm:.0f} mm)</td></tr>")
            el.append("</table>")
    except Exception:
        pass

    # ---- materials ----
    if config.include_materials:
        el.append("<h2>Materials</h2><ul>")
        el.append("<li>Yarn (see pattern for weight and colorway)</li>")
        el.append("<li>Appropriately sized crochet hook</li>")
        el.append("<li>Yarn needle, scissors, stitch marker</li>")
        el.append("</ul>")

    # ---- abbreviations ----
    if config.include_abbreviations:
        el.append("<h2>Abbreviations</h2><table>")
        el.append("<tr><th>Abbreviation</th><th>Meaning</th></tr>")
        for abbr, meaning in ABBREVIATION_GLOSSARY.items():
            el.append(f"<tr><td><strong>{_esc(abbr)}</strong></td><td>{_esc(meaning)}</td></tr>")
        el.append("</table>")

    # ---- instructions ----
    el.append(f"<h2>Instructions</h2>")
    for i, r in enumerate(items):
        num = r.round_number if hasattr(r, "round_number") else r.row_number
        stated = None
        for inst in r.instructions:
            if inst.stated_stitch_count is not None:
                stated = inst.stated_stitch_count
                break
        el.append(f"<div class=\"round\"><strong>{label} {num}:</strong> {_esc(r.source_text)}")
        if stated is not None:
            el.append(f" <span class=\"count\">({stated} sts)</span>")
        el.append("</div>")

    el.append(f"<footer>{_esc(config.footer_note)}</footer>")
    el.append("</body></html>")
    return "".join(el)


class PDFGenerator:
    """Generates print-ready HTML documents for validated patterns."""

    def __init__(self, config: "PDFConfig | None" = None):
        self.config = config or PDFConfig()

    def generate_html(self, pattern, report=None) -> str:
        return generate_pdf_html(pattern, validation_report=report, config=self.config)

    # alias used by the web API
    generate = generate_html

    def save(self, output_path: str, pattern, report=None) -> str:
        html = self.generate_html(pattern, report)
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        if out.suffix.lower() == ".pdf":
            # Print-to-PDF workflow: write HTML alongside the requested name.
            out = out.with_suffix(".html")
        out.write_text(html, encoding="utf-8")
        return str(out)
