"""Kawaii Halloween Mini Set - Novality NS 02 (Boo the Ghost, Pip the Pumpkin, Bramble the Bat).
Corrections applied: Pip leaf R2 fixed (`sc 4, inc x3, sc 4, inc x3` = 20, consumes all 14); Bramble wing Row 3 rewritten
with the big shell in the MIDDLE; pumpkin '40 mm around' -> '40 mm across'; witch-hat brim 22 mm; Pip's eyes placed ON rib
channels. All counts verified."""

P = dict(
    slug="halloween", title="Kawaii Halloween Mini Set", design_code="NS 02", terms="US terms", skill="Intermediate", time="1 - 1.5 hours each",
    hashtag="#KawaiiHalloweenSet", subtitle="Three pocket-sized amigurumi patterns",
    tagline=["Boo the ghost, Pip the pumpkin and Bramble the bat - three palm-sized minis",
             "in DK cotton, each about 5 cm tall, with big kawaii faces."],
    intro=("Three palm-sized Halloween minis in DK cotton: Boo the ghost with a ruffled hem and a tiny witch hat, Pip the pumpkin with six needle-sculpted ribs, "
           "and Bramble the bat with scalloped picot wings. Each is about 5 cm tall and takes an hour or so."),
    size_chip="5 - 5.5 cm each",
    stats=[("3", "PATTERNS IN THE SET"), ("5 cm", "TALL, EACH"), ("2.5 mm", "HOOK, DK COTTON"), ("6", "RIBS ON THE PUMPKIN")],
    feats=[("3", "minis: ghost,\npumpkin, bat"), ("48", "stitch ruffled\nhem on Boo"), ("6", "needle-sculpted\npumpkin ribs"), ("3", "picot scallops\nper bat wing")],
    palette=dict(accent="#B79BD1", deep="#6A4C93", pale="#F2ECF8", rule="#DDD2EA", hilite="#E8DDF3"),
    materials=[
        ("Yarn", "DK (#3) cotton: cream 10 g (Boo), pastel orange 10 g and sage green 2 g (Pip), lavender 10 g and pale pink 2 g (Bramble), black 5 g (hat, bat wing edge)."),
        ("Hook", "2.5 mm (US B/1 - C/2) for all three - a tight fabric so the minis hold their shape."),
        ("Safety eyes", "6 mm black safety eyes: two per toy, six in all. Or embroider with black floss."),
        ("Floss", "Black embroidery floss for mouths and cheeks; pink for blush stitches."),
        ("Stuffing & notions", "Polyester fibre filling about 5 g per toy; yarn needle; stitch marker; a long doll needle for sculpting Pip's ribs."),
    ],
    gauge=("24 sc around measures about 27 mm across when stuffed in DK on 2.5 mm (3.5 mm per stitch, 3.2 mm per round). Gauge is not critical for these minis - "
           "a looser gauge simply gives slightly bigger toys - but keep it tight enough that stuffing does not show."),
    abbreviations=[("MR", "magic ring"), ("ch", "chain"), ("sc", "single crochet"), ("hdc", "half double crochet"), ("dc", "double crochet"), ("inc", "increase (2 sc in one st)"),
                   ("invdec", "invisible decrease"), ("sl st", "slip stitch"), ("picot", "ch 3, sl st in first ch"), ("BLO / FLO", "back / front loop only"), ("FO", "fasten off"), ("(n)", "stitch count at row/round end")],
    techniques=[
        ("Magic ring & spiral", "All three bodies start with a magic ring and are worked in a continuous spiral. Move the marker every round."),
        ("Invisible decrease", "Front loops only of the next two stitches, yarn over, pull through both, yarn over, pull through two. Keeps the closings smooth on tiny pieces."),
        ("The ruffled hem", "Boo's hem doubles from 24 to 48 stitches in one round (2 sc in every stitch). Because the round below cannot stretch, the extra fabric must ripple - that is the ruffle. Work it loosely."),
        ("Needle sculpting", "Pip's ribs are pulled in with a long needle and a doubled strand of orange: go straight through the pumpkin from the bottom centre to the top centre, round the outside and back through, pulling firmly; repeat six times, evenly spaced."),
    ],
    sections=[
        dict(id="boo", title="3 · Boo the Ghost - cream", image="hero", caption="Boo, Pip and Bramble - each about 5 cm tall.",
             lead="A rounded dome with a ruffled hem, and a tiny witch hat. Boo is stuffed firmly up to the hem round; the ruffle is left open and floaty.",
             tables=[dict(heading="Body · R1 - R14", rounds=[
                 ("R1", "6 sc in MR", 6, "top of head"), ("R2", "inc in each st around", 12, ""), ("R3", "[1 sc, inc] x 6", 18, ""), ("R4", "[2 sc, inc] x 6", 24, ""),
                 ("R5", "sc in each st around", 24, ""), ("R6", "sc in each st around", 24, "eyes between R6 / R7, 5 sts apart"), ("R7", "sc in each st around", 24, ""),
                 ("R8", "sc in each st around", 24, ""), ("R9", "sc in each st around", 24, "stuff firmly"), ("R10", "sc in each st around", 24, ""),
                 ("R11", "sc in each st around", 24, ""), ("R12", "sc in each st around", 24, ""), ("R13", "BLO sc in each st around", 24, "hem line - stuff to here"),
                 ("R14", "inc in each st around", 48, "the ruffle - work loosely")],
                 finish="FO and weave in. The R13 back-loop round leaves a ridge that the ruffle flares from; the open bottom is the look. Body is about 27 mm across and 45 mm tall to the hem; 5 cm with the hat."),
                 dict(heading="Witch hat · black", rounds=[
                     ("R1", "4 sc in MR", 4, "tip"), ("R2", "[1 sc, inc] x 2", 6, ""), ("R3", "sc in each st around", 6, ""), ("R4", "[2 sc, inc] x 2", 8, ""),
                     ("R5", "sc in each st around", 8, ""), ("R6", "[3 sc, inc] x 2", 10, ""), ("R7", "sc in each st around", 10, ""), ("R8", "[4 sc, inc] x 2", 12, "cone done"),
                     ("R9", "FLO: inc in each st around", 24, "brim begins"), ("R10", "[1 sc, inc] x 12", 36, "brim - about 22 mm across")],
                     finish="FO with a long tail. Stuff the cone lightly, bend the tip over, and sew the hat to the top of Boo's head slightly off-centre over R1-R3. Add a band of orange floss round the base of the cone if you like."),
                 dict(heading="Arms · make 2 · cream", rounds=[("R1", "5 sc in MR", 5, ""), ("R2", "sc in each st around", 5, ""), ("R3", "sc in each st around", 5, ""), ("R4", "sc in each st around", 5, "")],
                     finish="FO with a long tail; do not stuff. Sew to the sides at R9-R10, pointing forward and slightly up."),
             ],
             steps=["Face - eyes between R6 and R7, 5 stitches apart. Embroider a small open 'o' mouth with black floss two rounds below the eyes, and a pink blush stitch under each eye."]),
        dict(id="pip", title="4 · Pip the Pumpkin - pastel orange", image="detail", caption="Six ribs pulled in with a doll needle; the eyes sit ON two rib channels.",
             lead="A squashed sphere, wider than tall, with six ribs pulled in by needle sculpting. The stem and leaf are sewn on top.",
             tables=[dict(heading="Body · R1 - R14", rounds=[
                 ("R1", "6 sc in MR", 6, "bottom"), ("R2", "inc in each st around", 12, ""), ("R3", "[1 sc, inc] x 6", 18, ""), ("R4", "[2 sc, inc] x 6", 24, ""),
                 ("R5", "[3 sc, inc] x 6", 30, ""), ("R6", "[4 sc, inc] x 6", 36, "about 40 mm across"), ("R7", "sc in each st around", 36, ""),
                 ("R8", "sc in each st around", 36, "eyes between R8 / R9, 6 sts apart"), ("R9", "sc in each st around", 36, ""), ("R10", "sc in each st around", 36, "stuff firmly"),
                 ("R11", "[4 sc, invdec] x 6", 30, ""), ("R12", "[3 sc, invdec] x 6", 24, ""), ("R13", "[2 sc, invdec] x 6", 18, "top up stuffing"), ("R14", "[1 sc, invdec] x 6", 12, "")],
                 finish="Do not close the 12-stitch top yet. Thread a doll needle with a long doubled strand of orange, anchor at the bottom centre, and pull six ribs (technique 4), evenly spaced every 6 stitches. Then cinch the top closed. About 40 mm across and 32 mm tall - squat, as a pumpkin should be."),
                 dict(heading="Stem · sage green", rounds=[("R1", "5 sc in MR", 5, ""), ("R2", "sc in each st around", 5, ""), ("R3", "sc in each st around", 5, ""), ("R4", "sc in each st around", 5, ""), ("R5", "sc in each st around", 5, "")],
                     finish="FO with a long tail; stuff with a wisp and sew to the top centre over the cinched hole, tilted slightly."),
                 dict(heading="Leaf · sage green", rounds=[("Found.", "ch 7", "chain", ""), ("R1", "sc in 2nd ch, sc in next 4, 3 sc in last ch, other side: sc in next 4, 2 sc in last ch", 14, "a small oval"),
                                                          ("R2", "sc 4, inc x 3, sc 4, inc x 3", 20, "consumes all 14")],
                     finish="FO with a long tail. Sew the leaf flat beside the stem, one point curling up. If you prefer a pointed leaf, sl st in the first stitch instead of working R2."),
             ],
             steps=["Face - choose two rib channels next to each other at the front; the eyes go ON those channels between R8 and R9, 6 stitches apart, so the ribs frame the face rather than run through it.",
                    "Embroider a small triangular nose and a wide smile with black floss two rounds below the eyes, pink blush stitches at the cheeks."]),
        dict(id="bramble", title="5 · Bramble the Bat - lavender", image="inhand", caption="Bramble's wings: three scallops each, the biggest in the middle.",
             lead="A round body with big pink-lined ears and two flat, scalloped wings worked in rows. The wings sew on by their straight top edge.",
             tables=[dict(heading="Body · R1 - R13", rounds=[
                 ("R1", "6 sc in MR", 6, ""), ("R2", "inc in each st around", 12, ""), ("R3", "[1 sc, inc] x 6", 18, ""), ("R4", "[2 sc, inc] x 6", 24, ""),
                 ("R5", "[3 sc, inc] x 6", 30, ""), ("R6", "sc in each st around", 30, ""), ("R7", "sc in each st around", 30, "eyes between R7 / R8, 6 sts apart"),
                 ("R8", "sc in each st around", 30, ""), ("R9", "sc in each st around", 30, "stuff firmly"), ("R10", "[3 sc, invdec] x 6", 24, ""),
                 ("R11", "[2 sc, invdec] x 6", 18, ""), ("R12", "[1 sc, invdec] x 6", 12, "top up stuffing"), ("R13", "invdec x 6", 6, "")],
                 finish="Cinch closed. About 33 mm across. Embroider two tiny fangs under a small smile with white and black floss."),
                 dict(heading="Ear · make 2 · lavender, then pink", rounds=[("R1", "4 sc in MR", 4, "tip"), ("R2", "[1 sc, inc] x 2", 6, ""), ("R3", "[2 sc, inc] x 2", 8, ""), ("R4", "[3 sc, inc] x 2", 10, ""), ("R5", "sc in each st around", 10, "")],
                     finish="FO with a long tail; flatten, and embroider a pink triangle inside each ear. Sew to the top of the head at R3-R4, about 6 stitches apart, pointing up."),
                 dict(heading="Feet · make 2 · lavender", rounds=[("R1", "5 sc in MR", 5, ""), ("R2", "sc in each st around", 5, ""), ("R3", "sc in each st around", 5, "")],
                     finish="FO; sew to the underside at R11-R12, 4 stitches apart."),
             ],
             steps=["Wing - make 2, black or lavender. Worked flat in rows; the straight Row 1 edge is the ATTACH edge and sews to the body. The scalloped Row 3 edge is the wing outline.",
                    "Row 1 - ch 13; sc in 2nd ch from the hook and in each ch across. Ch 1, turn. [12]",
                    "Row 2 - sc in each st across. Ch 1, turn. [12]",
                    "Row 3 (scallops) - sl st 2, (sc, hdc, picot, hdc, sc) in next, sl st 3, (sc, hdc, dc, picot, dc, hdc, sc) in next, sl st 2, (sc, hdc, picot, hdc, sc) in next, sl st 2. [26 stitches over 12 anchors] - the biggest scallop sits in the MIDDLE of the wing, so the wing points at its centre like a bat's.",
                    "FO leaving a long tail. Sew the Row 1 edge (12 stitches, about 42 mm) to the side of the body along R6-R8, scallops pointing out and slightly down. Each wing spans about 45 mm; tip to tip with the body about 12 cm."]),
    ],
    assembly=[
        ("Boo", "Eyes between R6/R7, 5 apart. Hat off-centre over R1-R3, tip bent. Arms at R9-R10. Mouth 'o' and blush. Stuffed to R13; ruffle open."),
        ("Pip", "Ribs first (six, with the doll needle) while the top is still open; then cinch, stem and leaf on top. Eyes ON two adjacent rib channels between R8/R9, 6 apart; nose, smile and blush."),
        ("Bramble", "Ears at R3-R4, 6 apart, pink lining. Eyes between R7/R8, 6 apart. Wings by the Row 1 edge along R6-R8 each side, big scallop centred. Feet under R11-R12. Fangs and smile."),
        ("Hanging loop (optional)", "For ornaments, ch 20 in matching yarn, sl st into the top centre of each toy and knot the ends inside."),
    ],
    checklist=["Boo: 1 body, 1 hat, 2 arms", "Pip: 1 body, 1 stem, 1 leaf", "Bramble: 1 body, 2 ears, 2 wings, 2 feet", "6 safety eyes (or floss)"],
    troubleshooting=[
        ("Boo's ruffle will not ripple.", "R14 must be a full 2 sc in EVERY stitch (24 to 48) and worked loosely, with R13 in back loops only so there is a ridge to flare from."),
        ("Pip is round, not squat.", "Stop at R10 for the straight rounds - three of them - and pull the ribs firmly; the sculpting compresses the height. Six ribs, 6 stitches apart."),
        ("Pip's eyes look wrong.", "Place them on two neighbouring rib channels so the ribs frame the face. Placed between channels, a rib runs through the eye."),
        ("Leaf comes out cupped.", "R2 must consume all 14 stitches: sc 4, inc x 3, sc 4, inc x 3 = 20. The old 'sc 4, inc x 3, sc 4' only used 11 and left it puckered."),
        ("Bat wings look like rectangles.", "They are rectangles until Row 3 - the scallop row is the whole shape. The 7-stitch shell must be the middle one, flanked by two 5-stitch shells."),
        ("Bat wing too narrow.", "The attach edge is 12 stitches (about 42 mm) but the wing spreads wider along the scallop edge. Sew only the Row 1 edge; leave the scallops free."),
        ("Witch hat brim too big.", "R10 is [1 sc, inc] x 12 = 36 for a 22 mm brim. If you worked inc in every stitch (48) the brim flops - pull R10 back."),
        ("Stuffing shows.", "Go down to a 2.25 mm hook; these are small and the fabric must be dense."),
    ],
    colorways=[("Classic cream", "#F3EDE1", "#2B2B2E"), ("Pumpkin orange", "#F1A97A", "#8DA57B"), ("Bat lavender", "#B79BD1", "#F3C4D3"), ("Ghostly white", "#FFFFFF", "#CFCFD6"), ("Charcoal", "#3A3A40", "#F1A97A"), ("Sage & oat", "#A9BFA4", "#EFE6D6")],
    colorways_caption="Left to right: classic cream Boo, pumpkin-orange Pip, lavender Bramble, then alternates - ghostly white, charcoal, sage and oat. Mix any body colour with any face.",
    terms_may=("Make as many finished minis as you like for yourself, gifts, or charity. Sell physical finished items made from this pattern in small batches, "
               "in shops, markets and online, provided credit is given to \"Novality Crochet Studio\"."),
    thanks="Tag your makes with #NovalityCrochetStudio and #KawaiiHalloweenSet - we love seeing your spooky trios. Thank you for supporting an independent pattern designer.",
    images={"hero": "hero.png", "inhand": "inhand.png", "detail": "detail.png", "colorways": "colorways.png"},
    image_prompts={
        "hero": "Product photograph of three tiny handmade crocheted amigurumi Halloween toys in a row: a cream ghost with a ruffled hem and tiny black witch hat, a pastel orange pumpkin with sculpted ribs and a sage stem, and a lavender bat with scalloped picot wings and pink ears, each about five centimetres tall, kawaii embroidered faces, on a soft cream linen surface, pastel backdrop, soft natural window light, shallow depth of field, clean etsy product photo",
        "inhand": "Three tiny handmade crocheted amigurumi Halloween toys, a cream ghost, an orange pumpkin and a lavender bat, sitting together in one open adult palm to show their five centimetre size, soft cream background, natural light, shallow depth of field, product photo",
        "detail": "Close-up macro photograph of a tiny handmade crocheted pastel orange amigurumi pumpkin showing six needle-sculpted ribs, a small sage green crocheted stem and leaf, 6 mm safety eyes and an embroidered smile, visible DK cotton stitch texture, soft light, shallow depth of field",
        "colorways": "Six tiny handmade crocheted amigurumi Halloween minis in a row, ghosts, pumpkins and bats in cream, pastel orange, lavender, white, charcoal and sage green cotton yarn, kawaii embroidered faces, on a cream linen surface, pastel backdrop, soft natural light, product photo",
    },
)
