"""Hamish the Highland Cow - Novality NS 01. Corrections applied: safety-eye washer lock is now called in the HEAD table
(before the head closes at R16) instead of in the muzzle section. All counts verified."""

P = dict(
    slug="hamish", title="Hamish the Highland Cow", design_code="NS 01", terms="US terms", skill="Intermediate", time="6 - 8 hours",
    hashtag="#HamishTheHighlandCow",
    tagline=["A shaggy, sturdy Highland cow with a flattened brow, a wide cream muzzle",
             "and a weather-beaten fringe. Worked in pieces so every proportion can be pinned first."],
    intro=("A shaggy, sturdy Highland cow with a flattened brow, a wide oat-cream muzzle, curved horns and a weather-beaten fringe of knotted yarn. "
           "Head, muzzle, body, legs, ears, horns and tail are worked separately so every proportion can be pinned and checked before a single seam."),
    size_chip="15 cm / 6 in sitting",
    stats=[("15 cm", "TALL, SITTING"), ("70 mm", "BODY WIDTH"), ("70 x 67 mm", "HEAD"), ("48 sts", "AROUND HEAD & BODY")],
    feats=[("48", "stitches around\nhead and body"), ("16", "head rounds -\none straight row"), ("43", "fringe knots in\nthree rows"), ("3", "sizes from one\npattern")],
    palette=dict(accent="#D39A5B", deep="#8C5320", pale="#F8EEE2", rule="#EAD9C4", hilite="#F3E1C8"),
    materials=[
        ("Yarn A - Ginger", "Worsted #4, ginger / rust, about 70 g. Head, body, legs, ears and tail."),
        ("Yarn B - Oat cream", "Worsted #4, oat cream, about 15 g. Muzzle, horns and inner ears."),
        ("Yarn C - Dark chocolate", "Worsted #4 or floss, dark brown, a few metres. Nostrils, mouth, hooves."),
        ("Yarn D - Rust (optional)", "Worsted #4 in a contrasting rust or a small tartan fabric square for the scarf."),
        ("Hook", "3.5 mm (US E/4) throughout."),
        ("Eyes", "Two 9 mm safety eyes (they sit under the fringe, so 9 mm rather than 6 mm keeps them visible)."),
        ("Stuffing & notions", "Polyester fibre filling about 45 g; yarn needle; stitch markers; pins; a 6 cm piece of card for cutting fringe."),
    ],
    gauge=("48 sc around measures about 70 mm across when stuffed (4.5 mm per stitch, 4.3 mm per round). Check on the head at R8. "
           "A slightly tight gauge is right for a cow this size - it keeps the head from sagging under the fringe."),
    abbreviations=[("MR", "magic ring"), ("ch", "chain"), ("sc", "single crochet"), ("inc", "increase (2 sc in one st)"), ("invdec", "invisible decrease"), ("sl st", "slip stitch"),
                   ("BLO", "back loop only"), ("FO", "fasten off"), ("st(s)", "stitch(es)"), ("(n)", "stitch count at round end")],
    techniques=[
        ("Magic ring & spiral", "Start every round piece with a magic ring; work in a continuous spiral with a marker in the first stitch of each round."),
        ("Invisible decrease", "Front loops only of the next two stitches, yarn over, pull through both, yarn over, pull through two."),
        ("The flattened brow", "The head is a 48-stitch sphere with only ONE straight round at full width (R9). That short middle is what flattens the top of the head into a brow for the fringe to sit on - do not add rounds here."),
        ("Back-loop hoof line", "Legs work R4 in back loops only. The unworked front loops leave a ridge that reads as the top of the hoof; the hoof itself is worked in dark brown."),
        ("Locking safety eyes", "Push the eye post through from the outside, press the washer on from the inside until it clicks, and tug-test. This must happen while the head is still open - before R14 - because the head closes to 6 stitches at R16."),
        ("Knotted fringe", "Cut 12 cm lengths of Yarn A, fold each in half, pull the loop through a stitch with the hook, pass the ends through the loop and tighten. Trim afterwards, never before."),
        ("Whip-stitch seams", "All pieces are sewn with the yarn tail through the last round's stitches into the body stitches, going round twice for anything that carries weight (head, legs)."),
    ],
    sections=[
        dict(id="head", title="3 · Head - Yarn A", image="hero", caption="Eyes between R10 and R11, 10 stitches apart; the fringe hides the top of them.",
             lead=("A 48-stitch sphere with one straight round, so the top flattens into a brow. Eyes go between R10 and R11, 10 stitches apart - "
                   "lock the washers at R13, before the head narrows."),
             tables=[dict(heading="Head · R1 - R16", rounds=[
                 ("R1", "6 sc in MR", 6, ""), ("R2", "inc in each st around", 12, ""), ("R3", "[1 sc, inc] x 6", 18, ""), ("R4", "[2 sc, inc] x 6", 24, ""),
                 ("R5", "[3 sc, inc] x 6", 30, ""), ("R6", "[4 sc, inc] x 6", 36, ""), ("R7", "[5 sc, inc] x 6", 42, ""), ("R8", "[6 sc, inc] x 6", 48, "full width - check gauge"),
                 ("R9", "sc in each st around", 48, "the ONLY straight round"), ("R10", "[6 sc, invdec] x 6", 42, "eyes between R10 / R11, 10 sts apart"),
                 ("R11", "[5 sc, invdec] x 6", 36, ""), ("R12", "[4 sc, invdec] x 6", 30, ""), ("R13", "[3 sc, invdec] x 6", 24, "LOCK EYE WASHERS NOW - stuff firmly"),
                 ("R14", "[2 sc, invdec] x 6", 18, ""), ("R15", "[1 sc, invdec] x 6", 12, "top up stuffing"), ("R16", "invdec x 6", 6, "")],
                 finish="Cinch the 6 stitches closed. The closed end is the BACK of the head; R1 is the front where the muzzle sits. Head measures about 70 mm wide x 67 mm tall.")],
             panels=[("Why lock the eyes at R13", "R16 closes the head to 6 stitches - after that you cannot get a washer inside. Insert the eyes at R10/R11 while the head is wide open, stuff, and press the washers on before you work R14.", "tip")]),
        dict(id="muzzle", title="4 · Muzzle - Yarn B", image="detail", caption="The wide oat muzzle is an oval, stuffed and sewn over R1-R7 of the head.",
             lead="A wide oval, not a circle - that is what makes a cow's nose. Stuff it firmly; it takes the nostrils and the mouth.",
             tables=[dict(heading="Muzzle · oval", rounds=[
                 ("Found.", "ch 7", "chain", ""),
                 ("R1", "sc in 2nd ch, sc in next 4, 3 sc in last ch, other side: sc in next 4, 2 sc in last ch", 14, "work round the chain"),
                 ("R2", "inc, 4 sc, inc x 3, 4 sc, inc x 2", 20, ""),
                 ("R3", "1 sc, inc, 4 sc, [1 sc, inc] x 3, 4 sc, [1 sc, inc] x 2", 26, ""),
                 ("R4", "BLO sc in each st around", 26, "turns the edge"), ("R5", "sc in each st around", 26, ""), ("R6", "sc in each st around", 26, ""),
                 ("R7", "sc in each st around", 26, "stuff firmly"), ("R8", "sc in each st around", 26, "")],
                 finish="FO with a long tail. Embroider two slanted dark nostrils on R5-R6, about 8 stitches apart, and a soft straight mouth line along the BLO ridge. Pin the muzzle over R1-R7 of the head, low and central, then sew round twice.")]),
        dict(id="body", title="5 · Body - Yarn A", image=None,
             lead="An egg with a wide, flat seat. Hamish sits, so the base is the widest part and it is stuffed hardest.",
             tables=[dict(heading="Body · R1 - R19", rounds=[
                 ("R1", "6 sc in MR", 6, "base"), ("R2", "inc in each st around", 12, ""), ("R3", "[1 sc, inc] x 6", 18, ""), ("R4", "[2 sc, inc] x 6", 24, ""),
                 ("R5", "[3 sc, inc] x 6", 30, ""), ("R6", "[4 sc, inc] x 6", 36, ""), ("R7", "[5 sc, inc] x 6", 42, ""), ("R8", "[6 sc, inc] x 6", 48, "widest - the seat"),
                 ("R9", "sc in each st around", 48, ""), ("R10", "sc in each st around", 48, ""), ("R11", "sc in each st around", 48, "back legs at R3 - R8"),
                 ("R12", "[6 sc, invdec] x 6", 42, ""), ("R13", "sc in each st around", 42, ""), ("R14", "[5 sc, invdec] x 6", 36, "front legs at R10 - R13"),
                 ("R15", "sc in each st around", 36, ""), ("R16", "[4 sc, invdec] x 6", 30, "stuff firmly"), ("R17", "[3 sc, invdec] x 6", 24, ""),
                 ("R18", "[2 sc, invdec] x 6", 18, "neck - head sews here"), ("R19", "[1 sc, invdec] x 6", 12, "")],
                 finish="Stuff very firmly, especially the base. FO leaving a long tail; the 12-stitch top is the neck and the head is sewn over it. Body is about 70 mm wide.")],
             panels=[("Sitting balance", "Hamish sits on the wide R8 seat with the back legs splayed forward either side. If he tips back, the base is under-stuffed or the back legs are sewn too far back - they belong at R3-R8 on the sides, toes forward.", "tip"),
                     ("Three sizes from one pattern", "As written (worsted, 3.5 mm) Hamish sits 15 cm tall. In DK on a 3.0 mm hook every piece comes out about 12 cm; in chunky on a 5.0 mm hook about 20 cm. The counts never change - only the yarn and hook.", "note")]),
        dict(id="legs", title="6 · Legs - make 4", image=None,
             lead="Start each leg in dark brown for the hoof, change to ginger after the BLO round. Back legs are stuffed firmly and sewn splayed; front legs hang.",
             tables=[dict(heading="Leg · make 4 · hoof in Yarn C, then Yarn A", rounds=[
                 ("R1", "6 sc in MR", 6, "Yarn C"), ("R2", "inc in each st around", 12, ""), ("R3", "[1 sc, inc] x 6", 18, ""),
                 ("R4", "BLO sc in each st around", 18, "hoof line - change to Yarn A after"), ("R5", "sc in each st around", 18, "Yarn A"),
                 ("R6", "[4 sc, invdec] x 3", 15, ""), ("R7", "sc in each st around", 15, ""), ("R8", "sc in each st around", 15, ""),
                 ("R9", "sc in each st around", 15, ""), ("R10", "[3 sc, invdec] x 3", 12, "stuff"), ("R11", "sc in each st around", 12, ""),
                 ("R12", "sc in each st around", 12, ""), ("R13", "sc in each st around", 12, ""), ("R14", "sc in each st around", 12, ""),
                 ("R15", "sc in each st around", 12, ""), ("R16", "sc in each st around", 12, "")],
                 finish="FO with a long tail. Stuff the hoof and lower leg firmly, the top lightly. Flatten the 12-stitch opening and whip-stitch it to the body: back legs at R3-R8 either side, angled forward; front legs at R10-R13 on the front, 8 stitches apart.")]),
        dict(id="ears", title="7 · Ears & horns", image=None,
             lead="Ears are flat teardrops that sit just below the horns, pointing out and slightly down. Horns are short curved cones in oat cream.",
             tables=[dict(heading="Ear · make 2 · Yarn A", rounds=[
                         ("R1", "6 sc in MR", 6, ""), ("R2", "inc in each st around", 12, ""), ("R3", "[1 sc, inc] x 6", 18, ""), ("R4", "sc in each st around", 18, ""),
                         ("R5", "sc in each st around", 18, ""), ("R6", "[1 sc, invdec] x 6", 12, ""), ("R7", "sc in each st around", 12, "")],
                         finish="FO with a long tail. Do not stuff. Flatten, fold the base in half and sew the folded base to the head at R9-R10, just below and outside each horn."),
                     dict(heading="Horn · make 2 · Yarn B", rounds=[
                         ("R1", "4 sc in MR", 4, "tip"), ("R2", "[1 sc, inc] x 2", 6, ""), ("R3", "sc in each st around", 6, ""), ("R4", "[2 sc, inc] x 2", 8, ""),
                         ("R5", "sc in each st around", 8, ""), ("R6", "[3 sc, inc] x 2", 10, ""), ("R7", "sc in each st around", 10, "stuff firmly"),
                         ("R8", "sc in each st around", 10, ""), ("R9", "sc in each st around", 10, ""), ("R10", "sc in each st around", 10, "")],
                         finish="FO with a long tail. Stuff firmly - a soft horn droops. Sew to the top of the head at R7-R8, about 14 stitches apart, curving up and outward. A few stitches of Yarn C around the base, if you like, read as the horn's dark ring.")]),
        dict(id="finish", title="8 · Tail, fringe & scarf", image="inhand", caption="Forty-three knots in three rows make the fringe; trim it only after all are in.",
             steps=["Tail - with Yarn A, ch 12, sl st in 2nd ch from the hook and in each ch back to the start (11 sl st). Cut six 8 cm strands of Yarn A, fold in half, knot through the last chain as a tassel and trim to 2.5 cm. Sew the tail to the centre back of the body at R6.",
                    "Fringe - cut about 45 lengths of Yarn A at 12 cm (wrap round the 6 cm card and cut once). Knot them into the head in three rows across the brow: Row 1 - 15 knots along R8, Row 2 - 14 knots along R7 staggered between them, Row 3 - 14 knots along R6. That is 43 knots. Comb downward and trim to 4-5 cm so the fringe covers the top half of the eyes, not the whole eye.",
                    "Scarf - with Yarn D, ch 8; sc in 2nd ch and each ch across (7). Ch 1, turn, sc in each st across until the strip is 28 cm long. FO. Wrap round the neck seam, cross at the front and tack with a few stitches. Or cut a 4 x 30 cm strip of tartan fabric and tie it.",
                    "Hooves - if you did not change colour at R4 of the legs, embroider a dark band around each R3-R4 with Yarn C.",
                    "Face - with Yarn C, two slanted nostrils on the muzzle at R5-R6, 8 stitches apart, and a straight mouth along the BLO ridge. Blush under the eyes if you like."]),
    ],
    assembly=[
        ("Head to body", "Pin the head onto the 12-stitch neck with the muzzle facing forward and the brow tilted very slightly down. Sew the head's R13-R14 stitches to the body's R17-R19, all the way round, twice. The head is heavy: use a doubled strand."),
        ("Muzzle", "Over R1-R7 of the head, low and central, oval lying wide. Sew round twice; embroider the nostrils and mouth after sewing."),
        ("Ears", "Fold the base and sew at R9-R10 of the head, just outside each horn, pointing out and a little down."),
        ("Horns", "R7-R8 on top of the head, about 14 stitches apart, curving up and out."),
        ("Back legs", "R3-R8 on the sides of the body, toes forward and splayed out so he sits on them."),
        ("Front legs", "R10-R13 on the front, 8 stitches apart, hanging straight down onto the back legs."),
        ("Tail, fringe, scarf", "Tail at R6 centre back. Fringe in three rows over R6-R8 of the head (43 knots), trimmed to cover the top half of the eyes. Scarf tied over the neck seam - it hides the join."),
    ],
    checklist=["1 head", "1 muzzle", "1 body", "4 legs (hoof in dark brown)", "2 ears", "2 horns", "1 tail", "~45 fringe lengths", "1 scarf"],
    troubleshooting=[
        ("The head sags forward.", "Stuff the head harder, sew the neck seam twice with a doubled strand, and check the head sits on R17-R19 of the body, not higher."),
        ("Hamish will not sit.", "The base (R1-R8) must be stuffed hardest. Back legs splayed forward at R3-R8 add a wide footprint; if he still tips, move them 2 rounds lower."),
        ("Fringe looks thin.", "You need all 43 knots in three staggered rows - one row always looks sparse. Trim only after every knot is in."),
        ("The eyes disappear.", "Trim the fringe to cover the TOP half of the eyes only, and use 9 mm eyes. Set them between R10 and R11, 10 stitches apart."),
        ("Cannot get the washer on.", "Lock the eyes at R13, while the opening is still 24 stitches. If the head is already closed, open R15-R16, fit the washers, and re-close."),
        ("Head looks like a ball, not a cow.", "Exactly one straight round at 48 (R9). An extra plain round rounds the brow off and the fringe slides forward."),
        ("The muzzle looks round.", "Start with the ch-7 oval and keep the BLO round at R4 - that ridge defines the wide nose. Sew it with the long axis horizontal."),
    ],
    colorways=[("Ginger", "#B8672A", "#EFE3CF"), ("Caramel", "#C99356", "#F3E6D2"), ("Highland black", "#2F2A28", "#D8CFC4"), ("Cream", "#E7D9C2", "#B79470"), ("Roan red", "#8E3F2B", "#EFDFCF")],
    colorways_caption="Left to right: ginger, caramel, Highland black, cream with a tan muzzle, roan red. Muzzle and horns in oat cream unless noted.",
    terms_may=("Make as many finished Hamishes as you like for yourself, gifts, or charity. Sell physical finished items made from this pattern in small batches, "
               "in shops, markets and online, provided credit is given to \"Novality Crochet Studio\"."),
    thanks="Tag your makes with #NovalityCrochetStudio and #HamishTheHighlandCow - we love seeing your coos. Thank you for supporting an independent pattern designer.",
    images={"hero": "hero.png", "inhand": "inhand.png", "detail": "detail.png", "colorways": "colorways.png"},
    image_prompts={
        "hero": "Product photograph of a handmade crocheted amigurumi Highland cow plush toy, ginger caramel worsted yarn, shaggy yarn fringe over the eyes, wide oat-cream muzzle, two small cream horns, sitting low with legs splayed, small rust tartan scarf, on a soft cream linen surface, pastel backdrop, soft natural window light, shallow depth of field, clean etsy product photo",
        "inhand": "A handmade crocheted amigurumi ginger Highland cow plush toy held in two open adult hands to show scale, about fifteen centimetres tall, shaggy yarn fringe and cream muzzle, soft cream background, natural light, shallow depth of field, product photo",
        "detail": "Close-up macro photograph of a handmade crocheted ginger amigurumi Highland cow face showing the knotted yarn fringe falling over 9 mm safety eyes, the wide oat-cream oval crocheted muzzle with embroidered nostrils, and small cream horns, visible stitch texture, soft light, shallow depth of field",
        "colorways": "Five handmade crocheted amigurumi Highland cow plush toys in a row, identical shape with fringe and horns, in ginger, caramel, black, cream and dark roan red yarn, on a cream linen surface, pastel backdrop, soft natural light, product photo",
    },
)
