"""Momo the Loaf Cat - Novality NS 06. Oval base ch 9 -> 48 sts; ears worked as three flat rows off R12; tail worked
into the body. All counts verified."""

P = dict(
    slug="momo", title="Momo the Loaf Cat", design_code="NS 06", terms="US terms", skill="Advanced beginner", time="2 - 2.5 hours",
    hashtag="#MomoTheLoafCat",
    tagline=["A cat in the loaf position - paws tucked, wider than tall, worked up from an oval base",
             "with the ears and tail crocheted straight on so there is nothing to sew but the face."],
    intro=("A cat in the classic loaf position: paws tucked under, wider than it is tall, worked in one piece up from a 48-stitch oval base. "
           "The ears are worked as three short rows straight off the body and the tail is crocheted onto the side, so there are no seams - only the face to embroider."),
    size_chip="7.9 x 5.2 x 4.3 cm",
    stats=[("7.9 cm", "LONG"), ("5.2 cm", "WIDE"), ("4.3 cm", "TALL"), ("48 sts", "OVAL BASE")],
    feats=[("0", "seams - ears and\ntail worked on"), ("48", "stitch oval base\nsets the shape"), ("16", "rounds, base\nto crown"), ("1.2:1", "wider than tall -\na true loaf")],
    palette=dict(accent="#A9A5B4", deep="#5C5769", pale="#F1F0F4", rule="#DEDCE4", hilite="#E7E5EC", accent2="#E8A0A6"),
    materials=[
        ("Main yarn", "Worsted #4, grey (or any cat colour), about 25 g."),
        ("Contrast", "Worsted #4 white, a few metres, for the chest and muzzle; pink floss for the nose; black floss for the eyes and mouth."),
        ("Hook", "3.5 mm (US E/4)."),
        ("Eyes", "Two 6 mm safety eyes, or embroider with black floss."),
        ("Also needed", "Polyester fibre filling about 12 g; yarn needle; stitch marker; pins."),
    ],
    gauge=("The 48-stitch oval base measures about 79 x 52 mm (4.5 mm per stitch, 4.3 mm per round). Check it after R4 - if the oval is much longer or rounder than that, "
           "your foundation chain is too loose or tight; re-chain at a steadier tension."),
    abbreviations=[("MR", "magic ring"), ("ch", "chain"), ("sc", "single crochet"), ("inc", "increase (2 sc in one st)"), ("invdec", "invisible decrease"), ("sl st", "slip stitch"),
                   ("BLO", "back loop only"), ("FO", "fasten off"), ("st(s)", "stitch(es)"), ("(n)", "stitch count at round end")],
    techniques=[
        ("The oval base", "Chain 9, then work down one side of the chain and back up the other, putting 3 sc in the last chain to turn the corner. The increases at both ends turn the strip into an oval and keep the long sides straight - that is what makes a loaf rather than a ball."),
        ("Back-loop turning round", "R5 is worked in back loops only. The unworked front loops make a crisp edge all round the base so Momo sits flat with a defined bottom."),
        ("Invisible decrease", "Front loops only of the next two stitches, yarn over, pull through both, yarn over, pull through two."),
        ("Ears worked on", "At R12, each ear is three short rows worked back and forth over 5 body stitches, decreasing to a point. No sewing, and they cannot fall off."),
        ("Tail worked on", "Join the yarn to the side of the body and crochet the tail directly out of the body stitches, then curl and tack it round the base."),
        ("Placing the face low", "A loaf cat's eyes sit low - on R8-R9, about a third of the way up the front. High eyes make a standing cat."),
        ("Embroidered features", "A pink 'V' nose with a short vertical line below and two small curves makes the classic cat mouth; two straight white stitches either side give whisker pads."),
    ],
    sections=[
        dict(id="body", title="3 · Base & body - one piece", image="hero", caption="A 48-stitch oval base worked straight up into the loaf.",
             lead="Start with the ch-9 oval. Four rounds of increases bring it to 48 stitches; R5 in back loops turns the edge; then the sides go straight up before the crown decreases.",
             tables=[dict(heading="Base & body · R1 - R16", rounds=[
                 ("Found.", "ch 9", "chain", ""),
                 ("R1", "sc in 2nd ch, sc in next 6, 3 sc in last ch, other side: sc in next 6, 2 sc in last ch", 18, "work round the chain"),
                 ("R2", "inc, 6 sc, inc x 3, 6 sc, inc x 2", 24, ""),
                 ("R3", "1 sc, inc, 6 sc, [1 sc, inc] x 3, 6 sc, [1 sc, inc] x 2", 30, ""),
                 ("R4", "2 sc, inc, 6 sc, [2 sc, inc] x 3, 6 sc, [2 sc, inc] x 2", 36, ""),
                 ("R5", "BLO: 3 sc, inc, 6 sc, [3 sc, inc] x 3, 6 sc, [3 sc, inc] x 2", 42, "back loops - the base edge"),
                 ("R6", "4 sc, inc, 6 sc, [4 sc, inc] x 3, 6 sc, [4 sc, inc] x 2", 48, "oval done: ~79 x 52 mm"),
                 ("R7", "sc in each st around", 48, ""), ("R8", "sc in each st around", 48, "eyes at R8 - R9, 6 sts apart, on a short end"),
                 ("R9", "sc in each st around", 48, ""), ("R10", "sc in each st around", 48, "stuff as you go"),
                 ("R11", "[6 sc, invdec] x 6", 42, ""), ("R12", "[5 sc, invdec] x 6", 36, "EARS worked here - see section 4"),
                 ("R13", "[4 sc, invdec] x 6", 30, "stuff firmly"), ("R14", "[3 sc, invdec] x 6", 24, ""), ("R15", "[2 sc, invdec] x 6", 18, ""),
                 ("R16", "[1 sc, invdec] x 6", 12, "top up, cinch closed")],
                 finish="Cinch the 12 stitches closed with the tail and bury it. The closed top runs along the length of the loaf. One short end of the oval is the FACE; the ears sit above it at R12 and the tail curls round from the other end.")],
             panels=[("Loaf proportions", "Length 79 mm, width 52 mm, height about 43 mm - wider than tall by 1.2 to 1. If your cat is taller than it is wide, you added straight rounds; R7-R10 are the only four.", "tip")]),
        dict(id="ears", title="4 · Ears & tail - worked on, not sewn", image="inhand", caption="Ears are three flat rows worked off R12; the tail is crocheted out of the side.",
             lead="Both are worked directly onto the body. Do the ears when you reach R12 (before the head closes), and the tail after the body is finished.",
             steps=["EARS - at R12, mark 5 stitches on the face end of the body, on each side of the centre line with 6 stitches between the two ears (so the pair sits about 27 mm apart). For each ear, join the main yarn with a sl st at the first marked stitch and work back and forth:",
                    "Row 1 - sc in next 5, ch 1, turn. [5]     Row 2 - dec, sc, dec, ch 1, turn. [3]     Row 3 - dec, sc. [2] - the ear tip.",
                    "FO, pull the tip to a point and bury the tail down through the ear. Embroider a small pink triangle inside each ear. The ears lean slightly forward over the face - if they lean back, you have joined them on the wrong end.",
                    "TAIL - after the body is closed, join the main yarn with a sl st at R6-R7 on one long side near the back end. Ch 1, then work 4 sc into the next 4 body stitches, working in a tiny spiral of 4 stitches around for 12 rounds (about 5 cm). FO leaving a tail.",
                    "Curl the tail round the base of the loaf along the long side and tack its tip down with two stitches so it hugs the body - a proper loaf cat keeps its tail wrapped.",
                    "CHEST - with white, embroider or crochet a small triangle on the face end below the muzzle line. The simplest way: 8-10 long straight stitches fanning from a point at R5 up to R8, between the paws."],
             panels=[("Tail as a spiral", "4 sc worked round and round makes a firm cord without stuffing. If your tail twists, you are pulling the yarn too tight - loosen a little and it will curl naturally.", "tip")]),
    ],
    assembly=[
        ("Face position", "Eyes at R8-R9 on one SHORT end of the oval, 6 stitches apart, centred. Low is right: a third of the way up."),
        ("Eyes", "6 mm safety eyes inserted before stuffing past R10 and locked, or two short horizontal black floss stitches with a tiny white highlight."),
        ("Nose & mouth", "A pink floss 'V' one round below the eyes, centred; a short black vertical line down from the point of the V and two small curves either side for the mouth."),
        ("Muzzle & chest", "Two or three white straight stitches under each side of the nose for whisker pads; a white fan of stitches on the chest below."),
        ("Ears", "Already worked at R12; embroider the inner pink triangles and check both tips are pinched to a point."),
        ("Tail", "Worked from R6-R7 on a long side, curled round the base and tacked at the tip."),
        ("Paws", "Optional: two short lines of main-colour stitches on the base edge at the front, 4 stitches apart, suggest the tucked paws."),
    ],
    checklist=["1 body with base (one piece, closed on top)", "2 ears worked on at R12", "1 tail worked on and tacked", "face embroidered: eyes, nose, mouth, whisker pads, chest"],
    troubleshooting=[
        ("Momo is round, not oval.", "The foundation chain sets the length - ch 9 gives 7 straight stitches each side. Keep the 6-stitch straight runs in R2-R6 exactly as written; putting increases in them rounds the shape off."),
        ("Taller than wide.", "R7-R10 are the only straight rounds. Stuff firmly but do not overstuff the height - press the top down gently when closing."),
        ("Ears in the wrong place.", "They belong at R12 above the FACE end, with 6 stitches between them. Work them before R13 so the head is still open enough to bury the tails."),
        ("The base is not flat.", "R5 must be worked in back loops only, and the base should be stuffed lightly at the bottom, firmly higher up. Stand Momo on a table and press down once."),
        ("The tail will not curl.", "Work the 4-stitch spiral a little tighter and tack the tip to the base with two stitches - it is meant to be sewn down, not to stay curled by itself."),
        ("Stuffing shows.", "36 sc should measure about 52 mm; if the fabric gapes, go down to a 3.0 mm hook."),
    ],
    colorways=[("Grey tabby", "#9E9AA6", "#F3F1EE"), ("Orange ginger", "#E0955A", "#F5EBDD"), ("Cream", "#F0E8D8", "#D9C1A0"), ("Black", "#2E2C31", "#F3F1EE"), ("Calico", "#EFE6D9", "#D28A54")],
    colorways_caption="Left to right: grey tabby, orange ginger, cream, black with a white chest, calico patches. Keep the nose pink and the eyes low.",
    terms_may=("Make as many finished Momos as you like for yourself, gifts, or charity. Sell physical finished items made from this pattern in small batches, "
               "in shops, markets and online, provided credit is given to \"Novality Crochet Studio\"."),
    thanks="Tag your makes with #NovalityCrochetStudio and #MomoTheLoafCat - we love seeing your loaves. Thank you for supporting an independent pattern designer.",
    images={"hero": "hero.png", "inhand": "inhand.png", "detail": "detail.png", "colorways": "colorways.png"},
    image_prompts={
        "hero": "Product photograph of a small handmade crocheted amigurumi grey cat in a loaf pose, low wide oval body with paws tucked under, small pointed ears, thin tail curled around the body, pink embroidered nose, small safety eyes set low, white embroidered chest, worsted yarn stitch texture, on a soft cream linen surface, pastel backdrop, soft natural window light, shallow depth of field, clean etsy product photo",
        "inhand": "A small handmade crocheted grey amigurumi loaf cat held in one open adult palm to show scale, about eight centimetres long, tail curled round the base, soft cream background, natural light, shallow depth of field, product photo",
        "detail": "Close-up macro photograph of a handmade crocheted grey amigurumi loaf cat face showing the low-set small safety eyes, pink embroidered V nose with a small mouth, white whisker-pad stitches and small pointed ears with pink inner triangles, visible stitch texture, soft light, shallow depth of field",
        "colorways": "Five small handmade crocheted amigurumi loaf cats in a row, identical loaf shape with tails curled round, in grey tabby, orange ginger, cream, black with white chest and calico patched yarn, on a cream linen surface, pastel backdrop, soft natural light, product photo",
    },
)
